version: "3.8"
services:
  main:
    build: .
    volumes:
      - .:/opt/app
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

